---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../base

patches:
  - path: grafana-tailscale.yaml
    target:
      kind: Service
      name: monitoring-grafana
  - path: prometheus-tailscale.yaml
    target:
      kind: Service
      name: monitoring-kube-prometheus-prometheus
