---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-kube-prometheus-prometheus
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "ml-prometheus"
    tailscale.com/tags: "tag:k8s"
