---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

# Add any environment-specific patches here
# patches:
#   - patch: |-
#       - op: replace
#         path: /data/server.insecure
#         value: "false"
#     target:
#       kind: ConfigMap
#       name: argocd-cmd-params-cm
